{
  pkgs,
  nixgl,
  polarbear,
  ...
}:

{
  home.packages = with pkgs; [
    fd
    ghostty
    openssh
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
    wl-clipboard
    fastfetch
    rclone
    mcp-nixos
    firefox
    claude-code
    opencode
    nixgl.packages.x86_64-linux.nixGLIntel
    polarbear.packages.x86_64-linux.nixvim
    polarbear.packages.x86_64-linux.dev-tools
    polarbear.packages.x86_64-linux.tools-net
    polarbear.packages.x86_64-linux.tools-nix
    polarbear.packages.x86_64-linux.tools-red
    polarbear.packages.x86_64-linux.tools-sre
    polarbear.packages.x86_64-linux.tools-ssh
    nb
  ];
}
